title: Ratinder Singh's Portfolio
description: Personal site to showcase my projects, skills, and resume.
baseurl: "" # leave this empty if using GitHub Pages with user/organization site (username.github.io)
url: "https://username.github.io" # replace with your actual GitHub Pages URL

# Theme
theme: jekyll-theme-minimal

# Author info
author:
  name: Ratinder Singh
  email: ratinder@example.com
  github: ratindersingh
  linkedin: ratindersingh
  twitter: ratind3r

# Navigation links (if theme supports it)
navigation:
  - title: About
    url: /about
  - title: Projects
    url: /projects
  - title: Blog
    url: /blog
  - title: Contact
    url: /contact

# Plugins (optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

# Social (used by some themes)
social_links:
  github: https://github.com/ratindersingh
  linkedin: https://www.linkedin.com/in/ratindersingh
  twitter: https://twitter.com/ratind3r
