title: Ratinder Singh's Portfolio
description: DevOps Engineer
baseurl: "" # Leave empty if using GitHub Pages for a user/organization site
url: "https://rsingh0101.github.io"

theme: jekyll-theme-cayman

author:
  name: Ratinder Singh
  email: ratinder021@gmail.com
  github: https://github.com/rsingh0101
  linkedin: https://www.linkedin.com/in/ratinder-singh-151113173/

header_pages:
  - about.md
  - projects.md
  - resume.md
  - contact.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
sass:
  style: compressed

include:
  - assets/css/custom.css
  
markdown: kramdown
highlighter: rouge
